export const assets = [
	/* Hack.assets.knight === self._kきし */
	['magician', '_mまじょ'],
	['knight', '_kきし'],
	['darkKnight', '_aあんこくきし'],
	['slime', '_sスライム'],
	['insect', '_iいもむし'],
	['spider', '_kくも'],
	['bat', '_kこうもり'],
	['dragon', '_dドラゴン'],
	['minotaur', '_mミノタウルス'],
	['boy', '_o男の子'],
	['girl', '_o女の子'],
	['woman', '_o女の人'],
	['enchantBookItem', '_m魔道書'],
	['explosion', '_bばくえん'],
	['ouroboros', '_uウロボロス'],
	['beam', '_bビーム'],
	['downStair', '_kくだりかいだん'],
	['upStair', '_nのぼりかいだん'],
	['warp', '_wワープ'],
	['castle', '_sしろ'],
	['flower', '_hはな'],
	['ruby', '_rルビー'],
	['trap', '_wわな'],
	['usedTrap', '_wわなかかった'],
	['heart', '_hハート'],
	['tree', '_k木'],
	['rock', '_iいわ'],
	['clayWall', '_tつちかべ'],
	['stoneWall', '_iいしかべ'],
	['box', '_tたからばこ'],
	['openedBox', '_tたからばこひらいた'],
	['skull', '_dドクロ'],
	['poo', '_uうんこ'],
	['pot', '_tつぼ'],
	['diamond', '_dダイヤモンド'],
	['magic', '_mまほうじん'],
	['usedMagic', '_mまほうじんひかった'],
	['coin', '_kコイン'],
	['sapphire', '_sサファイア'],
	['star', '_hほし'],
	['key', '_kかぎ'],
	['bomb', '_bばくだん']
];

export const events = {
	/* onplayerenter => onのった */
	'playerenter': 'のった',
	'playerstay': 'いる',
	'playerexit': 'おりた',
	'walkstart': 'あるきはじめた',
	'walkmove': 'あるいている',
	'walkend': 'あるきおわった',
	'triggerenter': 'ふれはじめた',
	'triggerstay': 'ふれつづけている',
	'triggerexit': 'ふれおわった',
	'collided': 'ぶつかった',
	'hpchange': 'HPかわった',
	'becomeidle': 'とまるとき',
	'becomewalk': 'あるくとき',
	'becomeattack': 'こうげきするとき',
	'becomedamaged': 'くらったとき',
	'becomedead': 'たおれたとき',
	'attacked': 'こうげきされた',
	'enterframe': 'つねに'
};
